[package]
name = "atelier"
version = "0.1.0"
edition = "2021"
description = "Workshop for ML models"
authors = ["FranciscoME <if.francisco.me@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/DeML-Research/Atelier"